### ISSUE TITLE
fetch.sh seems to fail due to lack of permissions on repositories

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [tkchia/build-ia16#1]
Those are the messages I get:
```
Cloning into 'gcc-ia16'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'newlib-ia16'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'binutils-ia16'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'reenigne'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'dosemu'...
Permission denied (publickey).
fatal: Could not read from remote repository.

```
By changing to https, it is enough to get it to fetch correctly.
Am I missing something about Git usage?

**Comment by tkchia** [comment]
Hello @TheFakeMontyOnTheRun,

Thanks for the report!  I will modify `fetch.sh` to fall back on using HTTPS to allow the toolchain to be fetched anonymously.

In the meantime, if you have an SSH key pair, you can [register the key with GitHub](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/).  This will also allow you to interact with GitHub via SSH in the future (note that [the user name will always be `git`](https://help.github.com/articles/testing-your-ssh-connection/)).

Thank you!

**Comment by TheFakeMontyOnTheRun** [comment]
Oh...I keep forgetting to do this!
Thank you for the reminder.
BTW, I'm having issues building the 86sim. Should I open a ticket? I'm note sure it is a required piece for the toolchain to work?

**Comment by tkchia** [comment]
Hello @TheFakeMontyOnTheRun ,

Thank you again for the report!  No, `./build.sh sim` is not really required for _using_ the toolchain.  It was included by @reenigne to serve as part of `gcc-ia16`'s regression test setup, and it is mainly useful to those of us who are tinkering on the toolchain itself.  If you do not need to stress-test the compiler, you can safely leave this step out.

But if you wish, you can open a new ticket with the detailed error messages you are getting from building `86sim`.  It builds fine on my system (Ubuntu Xenial), so I suspect it is having issues with different compilers; I will try to fix those if I know how.

Thank you!

**Comment by ecm-pushbx** [comment]
Had the same issue. I was confused by the error message. Looking at fetch.sh and reading this issue made me realise the error message was expected and that the fallback to https would make it work as it should. Maybe you can add a note about this to the readme?

```
build-ia16$ ./fetch.sh 
Cloning into 'gcc-ia16'...
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'gcc-ia16'...
```

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Thank you for the report! Yes, on second thought, the (intermediate) error messages can look quite confusing.

Before updating `README.md`, maybe I will see if I can directly tweak `fetch.sh` itself to give more informative status messages...

Thank you!

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

I have updated `fetch.sh`.  Thank you!
