### ISSUE TITLE
Please provide release tarballs

### ISSUE THREAD

**Issue by fuzxxl** [tkchia/build-ia16#13]
Hello!

I'd like to use your toolchain on a non-Ubuntu Linux box (well, it's a FreeBSD but it can run Linux programs).  It would be cool if you could distribute binary tarballs in addition to the PPA so users who do not run Ubuntu can easily install the toolchain as well.

**Comment by tkchia** [comment]
Hello @fuzxxl, I will look into how best to create binary tarballs.  Thank you!

**Comment by fuzxxl** [comment]
Thanks!  Greatly appreciated.

**Comment by tkchia** [comment]
Hello @fuzxxl,

I have created [some x86-64 binary tarballs](https://github.com/tkchia/build-ia16/files/4462411/tarballs.zip) for the Binutils and Newlib (C runtime and linker scripts) portions of the toolchain.  These do not include the C compiler itself yet, but you should already be able to use the assembler and linker to build some simple programs, e.g.
```
$ cat hello-s.s
	.code16

	.text

	.global	_start
_start:
	movw	$len,%cx
	movw	$msg,%dx
	movw	$1,%bx
	movb	$0x40,%ah
	int	$0x21

	movw	$0x4c00,%ax
	int	$0x21

	.data
msg:
	.ascii	"Hello, world\r\n"
	len = . - msg
$ ia16-elf-as -o hello-s.o hello-s.s
$ ia16-elf-ld -Tdos-mt.ld -o hello-s.exe hello-s.o
```
Please let me know if these tarballs work for you.  If they do, I will start publishing a more complete set of tarballs for the toolchain.

Thank you!

**Comment by fuzxxl** [comment]
Thanks!  Having the C compiler would be great, indeed.  It's the main reason I have been looking at this toolchain in the first place.

**Comment by fuzxxl** [comment]
The tarballs seem to work, too.  Thanks a lot!

**Comment by tkchia** [comment]
Hello @fuzxxl,

Thanks for your report!  I have added Linux/x86-64 tarballs for the toolchain -- including the C compiler --- on the [releases page](https://github.com/tkchia/build-ia16/releases).

**Comment by fuzxxl** [comment]
Greatly appreciated, thanks a lot!
