### ISSUE TITLE
CSEG jump tables and near/far code models

### ISSUE THREAD

**Issue by ghaerr** [tkchia/build-ia16#14]
Hello @tkchia,

I am wondering whether `ia16-elf-gcc` may have some features that could solve a problem I've been thinking about over at the ELKS project. That is, the ELKS kernel code segment is now around 55k, and there's not much room for more improvements, and not enough room for all drivers to be compiled in. So what I'm thinking about is essentially loadable kernel modules, or perhaps mixed near/far code procedures within a single executable. 

There would also be the issue of how the modules would be packed in the a.out header, or otherwise loaded.

All ELKS char and block drivers, as well as the filesystem drivers, use structures of function pointers, e.g. 'file_ops', etc. as entry points. I am not sure yet as to what functions in the main kernel need to be "called back" after entry, but, for those that don't, what could work is code thunks that reset CS: on entry, and a far return on exit. Since the entry points are always known and in the function pointer struct, that might provide an easy means to have a compiler automatically build entry thunks.

Another thought is compiling the whole kernel together in mixed near/far mode: a procedure-call-graphing tool (if any) could be used to determine which functions are "cyclically" called or need to be far, and the rest could be near.

I am not aware of what options ia16-elf-gcc has for near vs far code models, and the ability to produce thunks without writing asm code.

**Comment by tkchia** [comment]
Hello @ghaerr,

> I am not aware of what options ia16-elf-gcc has for near vs far code models, and the ability to produce thunks without writing asm code.

I guess a quick summary will be this:
  * `ia16-elf-gcc` does have some support for the "medium" memory model (far code, near data), at least when building MS-DOS `MZ` executables.
  * There is also some support for writing far functions in a mostly "small"-memory-model program, and for calling near functions from these far functions.  The later is still rather inefficient for now, and uses a fixed set of thunks that are compiled into `libgcc`.
  * There is no support yet for dynamic linking.

Internally, segment relocations are represented in the intermediate ELF `.o` files as special relocation entries (`R_386_OZSEG16`) which the Binutils linker will turn into `MZ` relocations.

Unfortunately it is still not very obvious to me how to port the support for segment relocations, and support for multiple text segments, to the ELKS or Minix `a.out` format.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> > * There is also some support for writing far functions in a mostly "small"-memory-model program, and for calling near functions from these far functions.

As an example, for the MS-DOS target and the small model, you can write something like
```
__attribute__ ((far_section)) int __far
far_greater_p (double x, double y)
{
  return x > y;
}
```
This will produce a function that is located outside the default text segment, but calls the internal runtime function `__gtdf2`, which is near, to do the floating-point comparison.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

Thank you very much for your explanations.

> ia16-elf-gcc does have some support for the "medium" memory model (far code, near data), at least when building MS-DOS MZ executables.

Is that support using command line options, or using the `far_section` attributes? Is there documentation on the ia16-elf-gcc memory model options somewhere, I couldn't find any.

> support for segment relocations, and support for multiple text segments, to the ELKS or Minix a.out format.

Are you referencing the extended header `a_trsize` and `a_tbase` members, or would another header be required for these relocations? I am not yet familiar the details on MZ relocations, but will read up on them.

**Comment by tkchia** [comment]
Hello @ghaerr,

> Is that support using command line options, or using the far_section attributes? Is there documentation on the ia16-elf-gcc memory model options somewhere, I couldn't find any.

The documentation is in the `ia16-elf-gcc` man page and also in the (more detailed) info file.  If you used `tools/build.sh` to build the toolchain under the ELKS tree (as `cross/`), the man page should appear with
```
man cross/share/man/man1/ia16-elf-gcc.1
```
and the info file with
```
info cross/share/info/gcc.info
```

The compiler flag for the medium memory model is `-mcmodel=medium`.  It basically forces all functions to be far functions, makes all function pointers far pointers as well, and gives each module its own text segment.  It currently only works with the MS-DOS target.

However, if you _only_ want to make a few functions far functions, you can stick to the small (`-mcmodel=small`) or tiny (`mcmodel=tiny`) memory model, and just specially mark the particular functions as far:
  * Both `__attribute__ ((far_section))` and `__far` together mean that the function will be a far function _and_ will be given its own separate segment.
  * `__far` alone means that the function can be called from outside the text segment, and will return to a 32-bit address; but the function code will still reside in the default text segment.

The info file for `ia16-elf-gcc` goes into a bit more detail on these specifiers.

Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> Are you referencing the extended header `a_trsize` and `a_tbase` members, or would another header be required for these relocations?

That is actually a good question.  I guess one thing that needs to be figured out first, is how to represent multiple text segments in the `a.out` file --- and from there try to figure out how to represent the relocations.

One possibility is to "cheat" a bit and just treat all the text segments as one single contiguous blob and let the `a.out` header's `a_text` be this blob's size.  Another is to somehow explicitly represent the separate text segments in the `a.out` structure.  It seems to me that either approach is going to have issues that need sorting out.

Thank you!

**Comment by ghaerr** [comment]
> One possibility is to "cheat" a bit and just treat all the text segments as one single contiguous blob and let the a.out header's a_text be this blob's size.

Certainly, there are many variations that one might imagine, when thinking about issues medium model might present. However, for ELKS, one use case that could be immediately useful would be that of compiling an entire application medium model, with no special treatment of any C functions, and no (or little) assembly language; for the shell, for example, which is close to the code segment limit. 

For that use case, it could be a good starting point to treat all the text segments as a single blob, and contain the relocation code in 'elks/fs/exec.c', reading the relocation data and relocating the text segment entirely in one kernel routine from the extended header. This would require a medium model version of libc and crt0.S also. Or - and I kind of like this idea, since it would keep the relocation code out of the kernel - the kernel could read in the text, data and relocation segments (placing relocation after bss), and the application startup crt0.S could patch the relocations itself, then discard the relocation memory.

After this worked, it could be considered to compile the entire kernel medium model, and relocate the kernel text segments in setup.S in the same way as crt0.S, although that would involve quite a bit more work because of the extensive assembly module bindings needing changing, but not too bad. 

Having support for ELKS medium-model applications would be a nice, controlled, first step for exploration of its continued use to the kernel. IIRC, there could be a few minor complications, since the ELKS kernel treats the extended header by assuming that the stack is below the data segment in certain circumstances, which we wouldn't want to change. I can look more into this if you think that the relocations could be output and processed in a blob for the entire text segment.

**Comment by ghaerr** [comment]
> One possibility is to "cheat" a bit and just treat all the text segments as one single contiguous blob and let the a.out header's a_text be this blob's size.

Certainly, there are many variations that one might imagine, when thinking about issues medium model might present. However, for ELKS, one use case that could be immediately useful would be that of compiling an entire application medium model, with no special treatment of any C functions, and no (or little) assembly language; for the shell, for example, which is close to the code segment limit. 

For that use case, it could be a good starting point to treat all the text segments as a single blob, and contain the relocation code in 'elks/fs/exec.c', reading the relocation data and relocating the text segment entirely in one kernel routine from the extended header. This would require a medium model version of libc and crt0.S also. Or - and I kind of like this idea, since it would keep the relocation code out of the kernel - the kernel could read in the text, data and relocation segments (placing relocation after bss), and the application startup crt0.S could patch the relocations itself, then discard the relocation memory.

After this worked, it could be considered to compile the entire kernel medium model, and relocate the kernel text segments in setup.S in the same way as crt0.S, although that would involve quite a bit more work because of the extensive assembly module bindings needing changing, but not too bad. 

Having support for ELKS medium-model applications would be a nice, controlled, first step for exploration of its continued use to the kernel. IIRC, there could be a few minor complications, since the ELKS kernel treats the extended header by assuming that the stack is below the data segment in certain circumstances, which we wouldn't want to change. I can look more into this if you think that the relocations could be output and processed in a blob for the entire text segment.

**Comment by tkchia** [comment]
Hello @ghaerr,

>  Or - and I kind of like this idea, since it would keep the relocation code out of the kernel - the kernel could read in the text, data and relocation segments (placing relocation after bss), and the application startup crt0.S could patch the relocations itself, then discard the relocation memory.

Thanks --- that sounds like an idea!  I will take a look at how I can modify `binutils-ia16` to support such a relocation scheme.  I guess a simplistic relocation format similar to the MS-DOS `MZ`'s --- where there is only one type of relocation, and the records are simply "places" to fix up --- should be quite feasible to do.

(Interestingly --- this is just a side note --- while there are references to `R_ABBS`, `R_RELLBYTE`, etc. `a.out` relocation types in the Minix header files, I have not been able to find any documentation about what they supposedly mean.  Hmm.)

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

Thank you for responding to my ideas.

> I guess a simplistic relocation format similar to the MS-DOS MZ's --- where there is only one type of relocation, and the records are simply "places" to fix up --- should be quite feasible to do.

I have read up on the MZ format. It seems the two-word relocation entries are basically just a segment/offset pair, which, when converted to a linear address, just point to a word in the image to which is added the the load segment offset. It appears to just be a list of segment references unmodified by the linker.

 > I will take a look at how I can modify binutils-ia16 to support such a relocation scheme. 

One thought, to start, might be to write a simple program that converts an MZ format executable to an ELKS a.out format. With this information, and now my understanding of the MZ format header, it seems pretty straightforward for a test-version of ELKS elks/fs/exec.c to load the MZ format directly, and adjust the relocations. The entire MZ executable may have to be loaded as a code segment, there isn't any information about code vs data segment in the MZ header, which ELKS wants.

If writing such a conversion program is indeed possible, that would allow the compiler chain to be used unmodified (but with changed compiler options for a test medium model program builtin elkscmd/test_medium) to compile an existing ELKS program. After that was working, the compiler could be modified to emit ELKS a.out output and the relocation information directly after the bss, and either the executable could self-relocate, or keep the relocation adjustment processing in the kernel.

**Comment by ghaerr** [comment]
> there are references to R_ABBS, R_RELLBYTE, etc. a.out relocation types in the Minix header files, I have not been able to find any documentation about what they supposedly mean.

A quick search of dev86 source shows that none of these relocation entries are used in any source, other than header files. I'm guessing they are either from a previous project, or just future planning.

**Comment by ghaerr** [comment]
Hello @tkchia,

>  to write a simple program that converts an MZ format executable to an ELKS a.out format.

In thinking of this further, it seems that an MZ format executable will not be able to be run on ELKS, as there is no way to determine the required separate code and data segments. Thus, your original idea of modifying the compiler to output MZ-style relocation data is a better approach. The ELKS kernel relocation handling will be quite straightforward, if the relocation data is read in along with the data segment, used to relocate segment offsets, then discarded or used as part of the 16k initial stack/heap.

**Comment by tkchia** [comment]
Hello @ghaerr,

After mucking around with the Binutils linker code a bit, I am now kind of gravitating towards explicitly representing separate text segments as such.

(Relocations placed in the text segment and data segment are already separately laid out in the `a.out` in any case --- at least per `a.out.h` --- and it turns out that jamming all the text segments together into one single blob will make the relocation system rather irregular.)

I am now experimenting with adding a new [`i386elks` file format back-end](https://github.com/tkchia/binutils-ia16/blob/65bf1cc0a0d61d6a4710b934bf9ab481ea48871b/bfd/i386elks.c) to Binutils.

The new back-end currently supports _an additional "far text segment"_ --- _currently up to 64 KiB_ --- by adding new optional fields to the .  It can also automatically add ELKS `a.out` relocations which can be placed in the near text segment, the near data segment, and the far text segment.  All this is (I suppose) still subject to change though, and the implementation internals are still a bit messy.

On the ELKS side, I will also try to look at how to modify the kernel and `libc` to deal with the new format.

Thank you!

**Comment by ghaerr** [comment]
Hello @tkchia,

Thank you for your work on this.

> I am now experimenting with adding a new i386elks file format back-end to Binutils.

Interesting. It turns out now is a good time to be discussing an alternative a.out header for ELKS.

Recently, changes were made to ELKS (via `ps` and `meminfo`) that allows easy inspection of running program's actual heap and stack usage. With `init` now working and supporting multiple serial and console `getty`s, along with configurable L2 buffers it has become easy to run too many programs and run out of memory. ELKS used to allocate a fixed 16k stack+heap, and require a minimum 4k stack. An analysis using the above tools showed this was quite in excess of what is needed, and the default allocation was halved, to 8k stack+heap, still retaining the 4k min stack requirement. Large memory-using programs use the -maout-chmem= option. The standard libc stdio buffer allocation was halved from 2048 to 1024 bytes. Many programs use no explicit heap allocation, and while others have arbitrarily used 4096 byte stack buffers while `read` won't ever return more than 1024 bytes.  With a little work, I think I can get most programs to run in a default 4k stack+heap total, but this will require separate default stack and heap entries in the a.out header, along with easy ways to set them from the compiler, and an easier-to-use `chmem` for tuning working set storage at runtime. The separate stack entry is required as the kernel will use a per-process stack minimum, instead of the current 4k for all.

I have a number of thoughts. First, however, it would be useful to discuss the design goals for such an expansion. Mine are:
- Must be simple for ELKS kernel at exec time.
- Small. The a.out header should not include lots of unused fields, but instead use an evolving linker-script to get the data from `gcc` to a.out as implemented and useful in ELKS. 
- Backwards compatibility for 'original' header, possibly not for 'extended' header used by unimplemented `bcc` stack-below-heap idea. Ideally maintain previous header entry meanings in new headers to reduce kernel code requirements.
- Separate heap and stack members, used when 'total' field is zero and sizeof(header) > 20h.

Separately, I'm not sure I understand the reasoning for continuing, *only in the ELKS a.out header itself*, using 32-bit quantities for everything. It seems a waste of space, and requires long arithmetic in the kernel needlessly. If we're going to move to a new a.out format for ELKS, this issue should be discussed as well.

Having said all this, I see no problem in keeping the text segments separate, but think it is critical that the code required in the ELKS kernel to process relocations be quite small, as the bigger problem is the kernel itself is quickly running out of space, much less so the applications.

> On the ELKS side, I will also try to look at how to modify the kernel and libc to deal with the new format.

I will be producing a few PRs soon to implement the internal separate heap and stack changes, and would like to work with you to create a linker script for that and the supporting text segment relocations.

**Comment by tkchia** [comment]
Hello @ghaerr,

> I have a number of thoughts. First, however, it would be useful to discuss the design goals for such an expansion. Mine are:
>   * Must be simple for ELKS kernel at exec time.
>   * Small. The a.out header should not include lots of unused fields, but instead use an evolving linker-script to get the data from gcc to a.out as implemented and useful in ELKS.

Thanks!  As you can see, I am currently adding the ELKS medium model support right inside Binutils itself, as a new file format back-end.  The GNU linker script language is pretty powerful --- and it was possible to fabricate the "small model" file format with script commands --- but it is limited in some ways.

(The flip side of this is that developing a back-end is somewhat harder.  Binutils's internals are structured like spaghetti...)

>   * Backwards compatibility for 'original' header, possibly not for 'extended' header used by unimplemented bcc stack-below-heap idea. Ideally maintain previous header entry meanings in new headers to reduce kernel code requirements.

I see that the kernel does support having the stack starting before the static data (via the `a_dbase` header field).  Is this something you think we should keep around?

**Comment by tkchia** [comment]
Hello @ghaerr,

> Separately, I'm not sure I understand the reasoning for continuing, _only in the ELKS a.out header itself_, using 32-bit quantities for everything. It seems a waste of space, and requires long arithmetic in the kernel needlessly. If we're going to move to a new a.out format for ELKS, this issue should be discussed as well.

I am guessing that this was a historical thing --- Minix used the same basic `a.out` format across several architectures, and some of them are 32-bit.

Thank you!

**Comment by ghaerr** [comment]
> I see that the kernel does support having the stack starting before the static data (via the a_dbase header field). 

That apparently unimplemented format uses the msh_dbase field for the start of the data segment offset, with the stack underneath. I don't see that dev86 actually implemented this format in any executable, but I could be wrong.  Most of the code is included only by CONFIG_EXEC_ELKS, but strangely that config option is also used to turn OFF a proper `vfork` implementation. This config option is almost always ON. My testing of proper `vfork` has been limited to date.

> Is this something you think we should keep around?

The only benefit I can see of the format would be to allow possible heap growth after program execution start by extending the data segment, provided contiguous memory is available. Otherwise, there's a definite benefit of the stack above heap approach by being able to share heap and stack space, especially when both sizes are shrunk considerably, which is my plan.

That said, I was thinking that the kernel code should be kept around for the time being, but turned default OFF, with the exception of the `vfork` issue. I see your PR for medium model kernel support also uses the same CONFIG_EXEC_ELKS - I would like to see that changed to a new CONFIG_EXEC_MMODEL to separate the two.

**Comment by ghaerr** [comment]
Hello @tkchia,

> I am guessing that this was a historical thing --- Minix used the same basic a.out format across several architectures, and some of them are 32-bit.

Does ELKS currently support actually running any MINIX executable? I'm guessing that even if the a.out headers matched, ELKS kernel ABI has changed enough nothing could safely run. And that brings up the issue of whether they should even be allowed to run (which begs the issue of whether revised a.out headers should keep longwords for backwards "compatibility").
