### ISSUE TITLE
Switch Case bad jmp address

### ISSUE THREAD

**Issue by ingcparga** [tkchia/build-ia16#18]
Hi, thanks for developing this toolchain.
A bit of context: I am currently working with a physical 8088 processor natively (without MS-DOS or BIOS routines). That is, I compile the codes and generate a binary file that I later program in an eeprom memory.

Testing the algorithms, I came across this case.
I have the following function that is nothing more than a 7 segment diplay binary decoder.

```
unsigned char byte2sevensegment(unsigned char num, unsigned char dot, unsigned char visible) // no está compilando bien, el salto del case no direcciona con las tablas de salto
{
  unsigned char sevensegment = 0;
  if (visible)
  {
    switch(num)
    {
      case 0x00:       //.gfedcba
        sevensegment = 0b00111111;
        break;
      case 0x01:       //.gfedcba
        sevensegment = 0b00000110;
        break;
      case 0x02:       //.gfedcba
        sevensegment = 0b01011011;
        break;
      case 0x03:       //.gfedcba
        sevensegment = 0b01001111;
        break;
      case 0x04:       //.gfedcba
        sevensegment = 0b01100110;
        break;
      case 0x05:       //.gfedcba
        sevensegment = 0b01101101;
        break;
      case 0x06:       //.gfedcba
        sevensegment = 0b01111101;
        break;
      case 0x07:       //.gfedcba
        sevensegment = 0b00000111;
        break;
      case 0x08:       //.gfedcba
        sevensegment = 0b01111111;
        break;
      case 0x09:       //.gfedcba
        sevensegment = 0b01101111;
        break;
      case 0x0A:       //.gfedcba
        sevensegment = 0b01110111;
        break;
      case 0x0B:       //.gfedcba
        sevensegment = 0b01111100;
        break;
      case 0x0C:       //.gfedcba
        sevensegment = 0b00111001;
        break;
      case 0x0D:       //.gfedcba
        sevensegment = 0b01011110;
        break;
      case 0x0E:       //.gfedcba
        sevensegment = 0b01111001;
        break;
      case 0x0F:       //.gfedcba
        sevensegment = 0b01110001;
        break;
      default:         //.gfedcba
        sevensegment = 0b00000000;
        break;
    }
    if (dot)          //.gfedcba
      sevensegment |= 0b10000000;
  }
  return sevensegment;
}

```
when compiling it gives me the following code in assembler (intel mnemonics, not at & t) 
```
byte2sevensegment:
	push	bp
	mov	bp,	sp
	sub	sp,	2
	mov	byte ptr [bp-1],	0
	cmp	byte ptr [bp+8],	1
	cmp	byte ptr [bp+8],	0
	je	.L32
	mov	al,	byte ptr [bp+4]
	xor	ah,	ah
	mov	ax,	ax
	cmp	ax,	15+1
	cmp	ax,	15
	ja	.L33
	shl	ax,	1
	mov	ax,	ax
	add	ax,	offset .L35
	mov	bx,	ax
	mov	ax,	word ptr [bx]    <------------------------ THE ISSUE!!! (1)
	jmp	ax
	.section	.rodata
	.p2align	1
	.p2align	2
.L35:
	.hword	.L34
	.hword	.L36
	.hword	.L37
	.hword	.L38
	.hword	.L39
	.hword	.L40
	.hword	.L41
	.hword	.L42
	.hword	.L43
	.hword	.L44
	.hword	.L45
	.hword	.L46
	.hword	.L47
	.hword	.L48
	.hword	.L49
	.hword	.L50
	.text
.L34:
	mov	byte ptr [bp-1],	63
	jmp	.L51
.L36:
	mov	byte ptr [bp-1],	6
	jmp	.L51
.L37:
	mov	byte ptr [bp-1],	91
	jmp	.L51
.L38:
	mov	byte ptr [bp-1],	79
	jmp	.L51
.L39:
	mov	byte ptr [bp-1],	102
	jmp	.L51
.L40:
	mov	byte ptr [bp-1],	109
	jmp	.L51
.L41:
	mov	byte ptr [bp-1],	125
	jmp	.L51
.L42:
	mov	byte ptr [bp-1],	7
	jmp	.L51
.L43:
	mov	byte ptr [bp-1],	127
	jmp	.L51
.L44:
	mov	byte ptr [bp-1],	111
	jmp	.L51
.L45:
	mov	byte ptr [bp-1],	119
	jmp	.L51
.L46:
	mov	byte ptr [bp-1],	124
	jmp	.L51
.L47:
	mov	byte ptr [bp-1],	57
	jmp	.L51
.L48:
	mov	byte ptr [bp-1],	94
	jmp	.L51
.L49:
	mov	byte ptr [bp-1],	121
	jmp	.L51
.L50:
	mov	byte ptr [bp-1],	113
	jmp	.L51
.L33:
	mov	byte ptr [bp-1],	0
	nop
.L51:
	cmp	byte ptr [bp+6],	1
	cmp	byte ptr [bp+6],	0
	je	.L32
	mov	al,	byte ptr [bp-1]
	or	al,	-128
	mov	byte ptr [bp-1],	al
.L32:
	mov	al,	byte ptr [bp-1]
	mov	al,	al
	mov	al,	al
	mov	sp,	bp
	pop	bp
	push	ss
	pop	ds
	ret
```
When I ran this code, the IP was grabbing a random address. When debugging step by step, I found that the instruction (1) has an error, since it currently indicates to take the data in a memory address (for the jump tables of the CASE) in DS and not in CS as it should happen.
By modifying the instruction in the binary from 
"mov ax, word ptr [bx]" 
to 
"mov ax, offset [bx]"  or "mov ax, word ptr CS:[bx]"
then the program worked correctly.
This I tried in different situations and the compiler output was always the same.
I have found other issues with operations on "union" type variables with "float" and "double", in the same way if I do something like C = A + B when A, B, C are "union", the IP at some point in the calculation is lost. I still do not find the problem as specific in the assembly instructions as the "switch case". Doing so I update you.
The ToolChain has been very useful to me and I am grateful for your work. 
P.D. Im currently working under DOSBox-X 0.83, Win-7.

**Comment by tkchia** [comment]
Hello @ingcparga,

Thank you.  This is not really a bug in `gcc-ia16` --- it assumes by default that both `ds` and `ss` point to your program's data segment (`.rodata`/`.data`/`.bss`).

Furthermore, in the default tiny memory model, it assumes that the code segment (`.text`) and the data segment (`.rodata`/`.data`/`.bss`) are the same, so `cs` = `ds` = `ss` = `.text` base = `.rodata`/`.data`/`.bss` base.

Since you are programming an EEPROM, I am guessing that what you really want is to have a read-only code segment (in ROM) and a read-write data segment (in RAM).  In that case:
  * You should probably use either the small memory model (`-mcmodel=small` compiler option) or maybe the medium memory model `-mcmodel=medium`).
  * You may also need to craft your linker script and startup code (`crt0.S` or some such), to properly copy the initial data segment contents from ROM to RAM, and to properly zero out `.bss`.

Thank you!

**Comment by ingcparga** [comment]
Thank you for your answer. You have a point. It's right about memory model Tiny, and all code is working with cs=ds=ss as definied in this model of memory... i lost this detail and now all has sense. And is true, im working with ds,ss != cs. 
Im not experiment yet with other models because im not arrive at this point, but i will experiment with -mcmodel=small now. 
Thank you for all.

**Comment by tkchia** [comment]
Hello @ingcparga,

Thank you.  Good luck!
