### ISSUE TITLE
How did you do these ASCII diagrams?

### ISSUE THREAD

**Issue by spacerace** [tkchia/build-ia16#2]
Hi, 

while reading this https://github.com/tkchia/build-ia16 I started to wonder, how do you make these diagrams with arrows?
Do you use any workflow-diagram-editor or do you copy&paste the characters and build it all by hand?

Doing this with some graphical tool would be really nice :)

**Comment by tkchia** [comment]
Hello @spacerace ,

Yes, basically I just copied and pasted the characters from a Unicode chart into a text editor. ☺  I did this because I figured that the diagram should be simple enough to do by hand (which it was).

Thank you!

**Comment by spacerace** [comment]
In "job-school" we used a program called DIA iirc. This was graphical workflow design - maybe it is able to output ASCII?

But anyway, my question has been answered, thank you :)
