### ISSUE TITLE
./build.sh binutils-djgpp fails with "undefined reference to `mbrtowc'"

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/build-ia16#23]
On an amd64 Debian 11 server.

```
  CCLD     readelf.exe
readelf.o:readelf.c:(.text+0x36143): undefined reference to `mbrtowc'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:1051: readelf.exe] Error 1
```

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

OK.  This is probably because I recently ported the `binutils-ia16` patches to a newer upstream Binutils.  I will probably need to replace one (more) call to `mbrtowc` with a call to `mbtowc`.

Thank you!

**Comment by ecm-pushbx** [comment]
Do I need to rerun `./fetch.sh` to get the update?

**Comment by ecm-pushbx** [comment]
I just did `git pull` in the `binutils-ia16` subdirectory, that seems to have worked.
