### ISSUE TITLE
Longs and Integers are the same size (both 16-bit)?

### ISSUE THREAD

**Issue by doodayev** [tkchia/build-ia16#29]
I'm not sure if this is the right place to put this, so sorry if it is but I just wanted to bring it up. I wrote a very simple C program that does basic arithmetic (add, subtract, multiply, and divide) on four different primitives: int, long, float, and double. Now I can understand for compatibility reasons why on newer 32-bit and 64-bit systems long would still be 32-bit even though integer is now 32-bit. What I don't understand however is in this particular case why long is the same size as integer. For reference, in Turbo C++, integers are still 16-bit but longs are 32-bit.

**Comment by tkchia** [comment]
Hello @doodayev,

`long` is definitely 32-bit on `gcc-ia16`.  However, the type alignment is 16 bits, not 32 bits.

The compiler also supports a `long long` type which is 64-bit.

There might be a problem with your test code &mdash; are you able to post it?

Thank you!

**Comment by tkchia** [comment]
```
$ cat test.c
#include <stdio.h>

int
main (void)
{
  static int a = 1;
  static long b = 2;
  static long long c = 3;
  static float d = 3.0;
  static double e = 4.0;
  printf ("sizeof (a) = %zu\n", sizeof (a));
  printf ("sizeof (b) = %zu\n", sizeof (b));
  printf ("sizeof (c) = %zu\n", sizeof (c));
  printf ("sizeof (d) = %zu\n", sizeof (d));
  printf ("sizeof (e) = %zu\n", sizeof (e));
  printf ("_Alignof (a) = %zu\n", _Alignof (a));
  printf ("_Alignof (b) = %zu\n", _Alignof (b));
  printf ("_Alignof (c) = %zu\n", _Alignof (c));
  printf ("_Alignof (d) = %zu\n", _Alignof (d));
  printf ("_Alignof (e) = %zu\n", _Alignof (e));
  return 0;
}
$ ia16-elf-gcc -Os test.c -o test.exe
$ emu2 test.exe
sizeof (a) = 2
sizeof (b) = 4
sizeof (c) = 8
sizeof (d) = 4
sizeof (e) = 8
_Alignof (a) = 2
_Alignof (b) = 2
_Alignof (c) = 2
_Alignof (d) = 2
_Alignof (e) = 2
```
Thank you!

**Comment by doodayev** [comment]
> Hello @doodayev,
> 
> `long` is definitely 32-bit on `gcc-ia16`. However, the type alignment is 16 bits, not 32 bits (i.e. among other things, there is no guarantee that the address of a `long` variable will be a multiple of 4).
> 
> The compiler also supports a `long long` type which is 64-bit.
> 
> There might be a problem with your test code — are you able to post it?
> 
> Thank you!

Sure. Now I have to say there's definitely a real possibility that I've messed something up. This is a conversion I made from C++ to C and so I may not be aware of how C treats different variable types when you're assigning them values from other types, maybe that's the problem. 

I'll post two code snippets. The first is the C version of the program and the second is the C++ version of the program.


#include <stdio.h>

int main()
{

    int int1, int2, int3;
    long long1, long2, long3;
    float float1, float2, float3;
    double double1, double2, double3;
    char choice;

    begin:
    printf("This program will show the difference \n");
    printf("between ints, longs, floats, and doubles. \n");
    printf("Enter two numbers ");
    scanf(" %lf", &double1);
    scanf(" %lf", &double2);
    printf("You've entered: %f %f \n", double1, double2);

    int1=double1;
    long1=double1;
    float1=double1;

    int2=double2;
    long2=double2;
    float2=double2;

    printf("Would you like to add, subtract, \n");
    printf("multiply or divide? \n");
    printf("Enter 1, 2, 3, or 4 respectively. \n");
    scanf(" %c", &choice);

    switch(choice)
    {

    case '1':
    int3=int1+int2;
    long3=long1+long2;
    float3=float1+float2;
    double3=double2+double1;
    break; 

    case '2':
    int3=int1-int2;
    long3=long1-long2;
    float3=float1-float2;
    double3=double2-double1;
    break;

    case '3':
    int3=int1*int2;
    long3=long1*long2;
    float3=float1*float2;
    double3=double2*double1;
    break;

    case '4':
    int3=int1/int2;
    long3=long1/long2;
    float3=float1/float2;
    double3=double2/double1;
    break;

    default:
    printf("INVALID!!! \n");
    int3=0;
    long3=0;
    float3=0;
    double3=0;
    }

    printf("With the operation you've requested, the values are: \n");
    printf("Integer: %d \n", int3);
    printf("Long: %d \n", long3);
    printf("Float: %f \n", float3);
    printf("Double: %f \n", double3);

    printf("Do it again? (Type y) \n");
    scanf(" %c", &choice);
    if(choice == 'y' || choice == 'Y')
    {
	goto begin;
    }
    return 0;
}

#include<iostream>
using namespace std;

int main()
{
  begin:
  int int1, int2, int3;
  long long1, long2, long3;
  float float1, float2, float3;
  double double1, double2, double3;
  char choice;

  cout << "This program will show the difference \n"
  << "between ints, longs, floats, and doubles. \n";
  cout << "Enter two numbers ";
  cin >> double1 >> double2;

  int1=double1;
  long1=double1;
  float1=double1;

  int2=double2;
  long2=double2;
  float2=double2;

  cout << "Would you like to add, subtract,\n multiply, or divide? \n";
  cout << "Enter 1, 2, 3, or 4 respectively. ";
  cin >> choice;

  switch(choice)
  {
    case '1':
    int3=int1+int2;
    long3=long1+long2;
    float3=float1+float2;
    double3=double1+double2;
    break;

    case '2':
    int3=int1-int2;
    long3=long1-long2;
    float3=float1-float2;
    double3=double1-double2;
    break;

    case '3':
    int3=int1*int2;
    long3=long1*long2;
    float3=float1*float2;
    double3=double1*double2;
    break;

    case '4':
    int3=int1/int2;
    long3=long3/long2;
    float3=float1/float2;
    double3=double1/double2;
    break;

    default:
    cout << "INVALID!!! \n";
    int3=0;
    long3=0;
    float3=0;
    double3=0;
  }

  cout << "With the operation you've requested, the values are: \n";
  cout << "Integer: " << int3 << endl;
  cout << "Long: " << long3 << endl;
  cout << "Float: " << float3 << endl;
  cout << "Double: " << double3 << endl;

  cout << "Do it again? (Type y) \n";
  cin >> choice;
  if(choice == 'y' || choice == 'Y')
  {
	goto begin;
  }
return 0;
}

**Comment by doodayev** [comment]
![image](https://github.com/tkchia/build-ia16/assets/61427449/d20c0641-0e75-4d29-bc22-5c71b6531a33)
And here's a screenshot of me running the C++ version on Turbo C++ and 64-bit GCC as well as the C version on 16-big GCC

**Comment by tkchia** [comment]
Hello @doodayev,

It seems you are using a conversion specification for `int` to print a `long` value?
```
  printf("Long: %d \n", long3);
```
should probably be
```
  printf("Long: %ld \n", long3);
```
Thank you!

**Comment by tkchia** [comment]
Hello @doodayev,

Incidentally, if you compile the program with warnings enabled (e.g. `-Wall`), then GCC will warn about the issue (and others) pretty quickly:
```
$ ia16-elf-gcc -mcmodel=medium -Wall -Os test.c -o test.exe
test.c: In function ‘main’:
test.c:74:20: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat=]
     printf("Long: %d \n", long3);
                    ^
$ gcc -Wall -Os test.c -o test  # GCC for host (Linux/x86-64)
test.c: In function ‘main’:
test.c:74:20: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat=]
   74 |     printf("Long: %d \n", long3);
      |                   ~^      ~~~~~
      |                    |      |
      |                    int    long int
      |                   %ld
test.c:16:5: warning: ignoring return value of ‘scanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   16 |     scanf(" %lf", &double1);
      |     ^~~~~~~~~~~~~~~~~~~~~~~
test.c:17:5: warning: ignoring return value of ‘scanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   17 |     scanf(" %lf", &double2);
      |     ^~~~~~~~~~~~~~~~~~~~~~~
test.c:31:5: warning: ignoring return value of ‘scanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   31 |     scanf(" %c", &choice);
      |     ^~~~~~~~~~~~~~~~~~~~~
test.c:79:5: warning: ignoring return value of ‘scanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   79 |     scanf(" %c", &choice);
      |     ^~~~~~~~~~~~~~~~~~~~~
```
Thank you!

**Comment by doodayev** [comment]
Ohhh. Thank you so much. You're right, I forgot to apply the l to the %ld. I need to practice C more often.
