### ISSUE TITLE
Check for libi86 fails if dosemu is not installed

### ISSUE THREAD

**Issue by JL2210** [tkchia/build-ia16#3]
I believe dosemu is required if you are to run `make check` on libi86.
Relevant line from `configure` output:
```
checking for dosemu... /bin/false
```
The build fails currently on my Gentoo ~amd64 machine.

**Comment by tkchia** [comment]
Hello @JL2210,

Oops --- sorry for the oversight!  I have [modified](https://github.com/tkchia/build-ia16/commit/a96163fd6acf2243c3a055de6a3a46835ef8502f) `build.sh` to skip the automatic testing on `libi86`, and simply go ahead and install the library files, if `dosemu` is not installed.

Do let me know if there is still an issue.

Thank you!

**Comment by JL2210** [comment]
Not a related one, but `fetch.sh` fails to pull in MPFR.

**Comment by tkchia** [comment]
Hello @JL2210,

I have updated the URL.  Thank you!
