### ISSUE TITLE
Need binary package for Ubuntu / Debian 'Focal'

### ISSUE THREAD

**Issue by mfld-fr** [tkchia/build-ia16#8]
Hello @tkchia , this is just a reminder on the right repository after https://github.com/jbruchon/elks/issues/288.

**Comment by tkchia** [comment]
Thanks @mfld-fr!  I am working on it.

(I am experiencing some problems getting the GCC code to link properly with newer versions of `libisl`; maybe I will follow what the ELKS scripts do, and disable `libisl` in the Ubuntu Focal build.)

**Comment by tkchia** [comment]
Hello @mfld-fr,

There should now be toolchain packages for Ubuntu Focal at my Launchpad repository (https://launchpad.net/~tkchia/+archive/ubuntu/build-ia16/+packages).

I will try to build stabler versions of the packages after I have run my `gcc-ia16` changes through regression testing.

Thank you!

**Comment by mfld-fr** [comment]
So fast... :astonished: !
