### ISSUE TITLE
"configure: error: gmp.h header not found" from ./build.sh isl

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/build-ia16#9]
These commands:

```
./build.sh clean
./build.sh binutils-debug
./build.sh binutils
./build.sh isl
```

Result in these errors:

```
[...]
hecking for stdint types... stdint.h (shortcircuit)
make use of stdint.h in include/isl/stdint.h (assuming C99 compatible system)
checking which gmp to use... system
checking gmp.h usability... no
checking gmp.h presence... no
checking for gmp.h... no
configure: error: gmp.h header not found
```

gmp-6.1.2.tar.bz2 has been downloaded by fetch.sh (I assume) and there is a subdirectory named gmp-6.1.2 in the build-ia16 root directory. There wasn't a gmp.h in the gmp-6.1.2 directory until I ran ./configure and make in there. Now it throws this error.

This is on a Debian 11 (testing) system, platform is amd64.

**Comment by ecm-pushbx** [comment]
Apparently I had to do "sudo make install" in the gmp subdirectory. The isl build seems to succeed after that.

**Comment by ecm-pushbx** [comment]
I consider this still a problem because it is not documented, though.

**Comment by ecm-pushbx** [comment]
The next step, `./build.sh gcc1`, failed until after I did `./configure && make && sudo make install` for both mpfr and mpc. This was the error message:

```
checking for the correct version of gmp.h... yes
checking for the correct version of mpfr.h... yes
checking for the correct version of mpc.h... no
configure: error: Building GCC requires GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
their locations.  Source code for these libraries can be found at
their respective hosting sites as well as at
ftp://gcc.gnu.org/pub/gcc/infrastructure/.  See also
http://gcc.gnu.org/install/prerequisites.html for additional info.  If
you obtained GMP, MPFR and/or MPC from a vendor distribution package,
make sure that you have installed both the libraries and the header
files.  They may be located in separate packages.
```

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Oops... yes, this is a bug.  I think it got masked on my system partly because I already installed a `libgmp-dev` package on it.

I will fix the `build.sh` script to actually build the multi-precision library files under the `build-ia16` tree.

Thank you!
